# Import all patches to ensure they are applied
from . import (  # noqa: F401
    areaplot,
    barplot,
    boxplot,
    clear,
    colorbar,
    errorbar,
    fillbetween,
    heatmap,
    hexbin,
    highlight,
    histogram,
    lineplot,
    pieplot,
    pointplot,
    scatterplot,
    seaborn_probe,
    regplot,
    kdeplot,
    candlestick,
    mplfinance,
    violinplot,
)
