"""Tests for the changelog's commit allowlist.

``[tool.semantic_release.changelog].exclude_commit_patterns`` decides which
commits reach ``CHANGELOG.md``.  Nothing reads it back, so when it is wrong
the release still succeeds and the only symptom is an entry that quietly is
not there.  It has now been wrong twice for exactly that reason: once
because the key sat under the wrong table and pydantic dropped it, and once
because no alternative admitted the ``!`` of a breaking commit -- so a major
release shipped without the entry explaining why it was a major.

These tests read the pattern from ``pyproject.toml`` rather than restating
it, and apply it the way ``ReleaseHistory.from_git_history`` does:
``pattern.match`` against the whole commit message.
"""

from __future__ import annotations

import re
import tomllib
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parents[2]

#: Types the changelog carries.  ``chore`` is deliberately not among them --
#: the release-time bundle refresh and the dependency bumps are housekeeping.
INCLUDED_TYPES = (
    "feat",
    "fix",
    "docs",
    "perf",
    "refactor",
    "test",
    "build",
    "ci",
    "style",
)

EXCLUDED_TYPES = ("chore", "revert")


def changelog_filters() -> list[re.Pattern[str]]:
    """Compile the exclusion patterns as python-semantic-release would.

    Returns
    -------
    list of re.Pattern
        The compiled contents of ``exclude_commit_patterns``.
    """
    config = tomllib.loads((PROJECT_ROOT / "pyproject.toml").read_text())
    patterns = config["tool"]["semantic_release"]["changelog"][
        "exclude_commit_patterns"
    ]
    return [re.compile(pattern) for pattern in patterns]


def is_excluded(message: str) -> bool:
    """Report whether a commit message would be kept out of the changelog.

    Mirrors ``ReleaseHistory.from_git_history``, which tests each pattern
    with ``match`` against the full message rather than the subject alone.

    Parameters
    ----------
    message : str
        A complete commit message, subject and body.

    Returns
    -------
    bool
        ``True`` when at least one pattern matches, i.e. the commit is
        dropped from the changelog.
    """
    return any(pattern.match(message) for pattern in changelog_filters())


@pytest.mark.parametrize("commit_type", INCLUDED_TYPES)
@pytest.mark.parametrize("scope", ["", "(deps)", "(core)"])
def test_a_breaking_commit_still_reaches_the_changelog(
    commit_type: str, scope: str
) -> None:
    """A ``!`` marker must not remove a commit from the changelog.

    This is the regression the file exists for: the written-out form of the
    allowlist ended every alternative in ``): `` or ``: ``, which
    ``feat(deps)!: `` does not match.
    """
    assert not is_excluded(f"{commit_type}{scope}!: a breaking change")


@pytest.mark.parametrize("commit_type", INCLUDED_TYPES)
@pytest.mark.parametrize("scope", ["", "(deps)", "(core)"])
def test_an_ordinary_commit_reaches_the_changelog(
    commit_type: str, scope: str
) -> None:
    """Admitting ``!`` must not have narrowed what was already admitted."""
    assert not is_excluded(f"{commit_type}{scope}: an ordinary change")


@pytest.mark.parametrize("commit_type", EXCLUDED_TYPES)
@pytest.mark.parametrize("scope", ["", "(deps)"])
@pytest.mark.parametrize("marker", ["", "!"])
def test_housekeeping_stays_out(
    commit_type: str, scope: str, marker: str
) -> None:
    """``chore`` and ``revert`` are excluded, breaking marker or not.

    The ``!`` is admitted per type, not globally, so widening the pattern
    must not have let housekeeping back in through the marker.
    """
    assert is_excluded(f"{commit_type}{scope}{marker}: housekeeping")


@pytest.mark.parametrize(
    "message",
    [
        "feature: a type that merely starts with an allowed one",
        "circle: another of those",
        "1.20.0\n\nAutomatically generated by python-semantic-release",
        "Merge branch 'main' into a-branch",
        "not a conventional commit at all",
    ],
)
def test_what_is_not_a_listed_type_stays_out(message: str) -> None:
    """The allowlist matches whole types, not prefixes of them."""
    assert is_excluded(message)


def test_the_body_does_not_decide_it() -> None:
    """Only the subject is consulted, however long the body is.

    ``.`` does not cross a newline, so a pattern anchored at the start reads
    the subject and stops.  Worth pinning: a body that happened to contain
    the word ``chore`` should not evict the commit.
    """
    kept = "feat(deps)!: a breaking change\n\nchore: this line is not the subject\n"
    dropped = "chore: housekeeping\n\nfeat: this line is not the subject either\n"

    assert not is_excluded(kept)
    assert is_excluded(dropped)
