project:
  type: website
  output-dir: _site


metadata-files:
  - api/_sidebar.yml


website:
  title: "Py maidr"

  site-url: https://py.maidr.ai/
  repo-url: https://github.com/xability/py-maidr
  issue-url: https://github.com/xability/py-maidr/issues/new/choose
  repo-actions: [issue]

  page-navigation: true
  bread-crumbs: true

  navbar:
    background: light
    # logo: quarto.png
    logo-alt: "Maidr logo."
    logo-href: https://py.maidr.ai/
    title: Py maidr
    collapse-below: lg
    left:
      - file: index.qmd
        text: "Welcome"
      - file: examples.qmd
        text: "Examples"
      - text: "API Reference"
        href: api/
    right:
      - icon: github
        href: https://github.com/xability/py-maidr
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: ’^(?:http:|https:)’


# quartodoc:
#   package: maidr
#   dir: api
#   sidebar: _sidebar.yml
#   style: pkgdown
#   title: "PyMAIDR"
#   renderer:
#     style: markdown
# #  sections:
# #    - title: Plot API
# #      desc: ""
# #      contents:
# #        - bar
# #        - box
# #        - count
# #        - heat
# #        - hist
# #        - line
# #        - scatter
# #
#    - title: Maidr API
# #      desc: ""
# #      package: maidr.core
# #      contents:
# #        - Maidr.render
# #        - Maidr.show
# #        - Maidr.save_html


filters:
  - interlinks
  - line-highlight


interlinks:
  fast: true
  sources:
    numpy:
      url: https://numpy.org/doc/stable/
    python:
      url: https://docs.python.org/3/

quartodoc:
  package: maidr
  dir: api
  title: API Reference
  style: pkgdown
  dynamic: true
  render_interlinks: true
  sections:
    - title: Displaying an accessible and interactive plot with multimodal formats
      desc: >
        Plots genereated by **Matplotlib** or **Seaborn** can be displayed in MAIDR format in default browser.
        Input plot object as an argument in `maidr.show()`.
      contents:
        - Maidr.show
    - title: Saving a maidr plot as an HTML file
      desc: >
        Save a plot as an HTML file with `maidr.save_html()`.
      contents:
        - Maidr.save_html
